### ISSUE TITLE
How will vendors' work be coordinated?

### ISSUE THREAD

**Issue by waldoj** [AlaskaDHSS/EIS-Modernization#100]
How will concurrent work between vendors be coordinated?

**Comment by randyhart** [comment]
The product owner and the Project Management office will manage multiple procurements and vendor activities.  Development work will happen in Git branches.  Pull requests will be created against first staging, and later master branches.  The State will review and accept Pull Requests. Further, all commits will engage our CI service to run tests, etc.  Various live environments may be concurrently running to support development and integration efforts.
