### ISSUE TITLE
Will FOSS-integrating COTS be considered?

### ISSUE THREAD

**Issue by waldoj** [AlaskaDHSS/EIS-Modernization#114]
Will Alaska DHSS consider technology agnostic commercial-off-the-shelf solutions that incorporate open source technologies and that can be integrated with legacy and current technologies?

**Comment by randyhart** [comment]
Yes, we will consider commercial off-the-shelf solutions that incorporate open source technology if it can solve a problem for our users. We prefer that it be open source and SaaS.
