### ISSUE TITLE
Will mobile be considered?

### ISSUE THREAD

**Issue by waldoj** [AlaskaDHSS/EIS-Modernization#115]
Would Alaska DHSS be willing to take advantage of new technologies to support client's needs by considering mobile solutions for clients to engage with the current DHSS system as the EIS modernization effort is progressing?

**Comment by randyhart** [comment]
We are interested in new technologies as long as they are well supported, open source, and well documented. We want to stay away from unproven technologies that may or may not be around in the future. We would consider mobile solutions, if they appeared to address user needs. However, many of our end users have device, connectivity and bandwidth constraints.
