### ISSUE TITLE
Approach to architecture, tech stack in the prototype MVP?

### ISSUE THREAD

**Issue by randyhart** [AlaskaDHSS/EIS-Modernization#116]
Is the current prototype also fulfilling the role of the MVP defined in the dev ops document, or is that a separate effort? Any plans for further public discussion of the approach, architecture and technology stack outlined there?

**Comment by randyhart** [comment]
The DevOps MVP currently uses an empty (freshly generated) asp.net app.  We hope to substitute the prototype for this empty app soon.  Alaska has been experimenting with various DevOps approaches/tools (IaaS, PaaS, etc).  We are moving towards this stack: .NET Core, Azure AppService (Azure PaaS), VSTS for git repos, VSTS for CI build pipeline, VSTS for CD release pipeline.  We have a private repo with code and documentation around the approaches and tools we have investigated -- we are working on open sourcing this repository soon.

**Comment by cefolar** [comment]
We used that stack successfully for some prototyping work at the State of MS with good results.  You can use Yeoman to scaffold it over an empty app.  Integrated GIT with the Azure deployment stream and were able to very quickly build functionality.
