### ISSUE TITLE
Are products being considered, or only services?

### ISSUE THREAD

**Issue by waldoj** [AlaskaDHSS/EIS-Modernization#117]
As part of Alaska's modular procurement strategy, is the state considering products as well as services? We have been working on products generally in the government digital services space, specifically in the Medicaid/HHS eligibility space, and would like to understand if procurement of software or Software-as-a-Services is being considered as part of the overall procurement strategy.

**Comment by randyhart** [comment]
Yes, if something already exists (a Software as a Service) that provides the functionality our users need, we are open to that as a potential solution or part of a solution for a given module. We prefer that it is open source.
