### ISSUE TITLE
Planned integration platform

### ISSUE THREAD

**Issue by cefolar** [AlaskaDHSS/EIS-Modernization#130]
As part of the technology stack evaluation and decision has there been any decision or evaluation on platform for the service fabric architecture?

**Comment by sztaylorakgov** [comment]
I believe we have not yet evaluated Azure Service Fabric.  To date, we have focused on evaluating Azure App Service PaaS.  If there are specific benefits you would see in leveraging Azure Service Fabric, please feel free to add a clarifying comment here and I will check with the team to see if we have any additional feedback.

**Comment by cefolar** [comment]
I appreciate the insight, was just interested in what the thinking was behind the integration approach.  If the team was looking at a traditional ESB or more of a micro-service fabric.  Given the rest of the stack is leaning toward .NET Core and the other Azure technologies the Azure Service Fabric definately makes sense.  We look forward to following the progress of the project - thanks!
