### ISSUE TITLE
Application containerization

### ISSUE THREAD

**Issue by cefolar** [AlaskaDHSS/EIS-Modernization#131]
Along with using App Services on Azure has there been any consideration for a containerization approach and if so has the state consiered the orchestration preference such as Docker, Kubernetes, Mesos, etc?

**Comment by sztaylorakgov** [comment]
We did some early work on containerization, leveraging Docker and some other technologies in the dev environment.  We have not yet evaluated Docker and container orchestration as a full DevOps path to production.  I don't have experience with Kubernetes and Mesos, though these look at first glance like they address similar problems to the App Service architecture (clustering servers w/ black-boxed services like load-balancing, scaling, etc.).  I will get some additional feedback from the team when folks are back in the office next week to clarify how far we've gone with containerization and where we hope to go.  It may take a day or two, but we will respond as soon as we can.  Thanks again for the interest and questions!
