### ISSUE TITLE
Division of Labor

### ISSUE THREAD

**Issue by tlovering** [AlaskaDHSS/EIS-Modernization#182]
Your choice of tech stack may limit our ability to respond to this and future solicitations. Have you given any thought to separating front-end development (e.g. UX research, design, development) from server-side development? 

If so, would that be a consideration for this first RFP, or more likely for future, larger elements of the project? 

This might potentially open things up for more vendors to respond.

**Comment by cefolar** [comment]
Was going to ask that as well - but was going to recommend just seperate scoring for tech and UX experience.  Definitely want strong UX experience equally as the strong dev experience.  The risk is a pure software dev shop that produces subpar UX.

**Comment by randyhart** [comment]
We appreciate the feedback.  However, we feel the scope of work envisioned as part of this RFP is narrow enough to be handled in a single procurement.  It's worth noting that subcontracting is allowed as part of responding to the RFP.

The weights of the different evaluation criteria are still under consideration - how the vendor team approaches design/UX is an important aspect of what will be built and we'll make sure that's clear in our RFP.

**Comment by mheadd** [comment]
Just an FYI since you've had questions about this project - the RFP has now been issued, and you can [find details here](https://github.com/AlaskaDHSS/RFP-Search-Unification).
