### ISSUE TITLE
Response Scoring Feedback

### ISSUE THREAD

**Issue by cefolar** [AlaskaDHSS/EIS-Modernization#185]
We noticed that you have applied 40% of the scoring on price.  Given this is a strategic initiative for the Departments and the State of Alaska, there is a risk that a low budget, less qualified vendor may attempt to "buy" the work and could present a risk to the momentum that you guys have gained if they underperform.  Given that the project is capped at $300k, there doesn't appear to be a significant risk to the state if they have a higher qualified bidder that might have a slightly higher premium but significantly more experience.  When the prime objective is to really get a highly capable partner, we have seen other states go to numbers like 25% on price and the balance in experience and quals.  We really commend you guys on your approach and look forward to following the progress.

**Comment by jongeselle** [comment]
This is a great point. We are actually exploring a reduction in scoring of price for the reasons you identify. It requires some internal approvals to make this change, but we are hopeful that we'll be able to move some of those points into other evaluation sections.

**Comment by cefolar** [comment]
@jongeselle as you guys are exploring that, similar to the discussion in #182 - it might also be beneficial to distribute some percentage to the Human Centered Design/UX-UI experience/process so that you balance pure code slinging with good UX design principals to protect against a well coded app that misses the mark on the human experience side.

**Comment by mheadd** [comment]
Just an FYI since you've had questions about this project - the RFP has now been issued, and you can [find details here](https://github.com/AlaskaDHSS/RFP-Search-Unification).
