### ISSUE TITLE
Working RFP Draft Question - Search Capabilities

### ISSUE THREAD

**Issue by ChrisLetterman** [AlaskaDHSS/EIS-Modernization#198]
What are the desired search capabilities beyond basic results of a client or an applicant? For example, should a search result include current application status? Or identify the responsible DPA team(s)/resource(s) assigned to unworked applications?  In Sect 2.01 there is an inferred emphasis on decreasing time necessary for DPA staff to obtain critical information. What constitutes critical information? Will those data points be expected in all search returns and are they the same across EIS and ARIES systems?

**Comment by mheadd** [comment]
We expect that user research conducted post-award will help identify the critical elements that need to be returned in the search results.
