### ISSUE TITLE
Working RFP Draft Question - DHSS Performance Measures

### ISSUE THREAD

**Issue by ChrisLetterman** [AlaskaDHSS/EIS-Modernization#199]
DHSS has posted Performance Measures on the OMB website – is there an expectation that some search results need to specifically address Performance Measures? If so, which ones?

**Comment by mheadd** [comment]
Our expected business outcome metrics are listed on our [product roadmap](https://app.mural.ly/t/gsa6/m/gsa6/1493828126408/2c1fd30717381a20f4bf251e57a1c344f9e2c3ba).
