### ISSUE TITLE
Working RFP Draft Question - Application Statuses

### ISSUE THREAD

**Issue by ChrisLetterman** [AlaskaDHSS/EIS-Modernization#200]
What application statuses are to be included for applications of a person/household? Is there a common terminology and definition of status conditions between the EIS and ARIES systems?

**Comment by ChrisLetterman** [comment]
Question clarification - The User Journey & Prototype mention: RECEIVED, REGISTERED, OPEN, CLOSED, PENDING - do these represent the all the status conditions in EIS & ARIES?

**Comment by mheadd** [comment]
We expect that clarification of these statuses will take place post award, during user research.
