### ISSUE TITLE
Working RFP Draft Question - Identity and Access

### ISSUE THREAD

**Issue by ChrisLetterman** [AlaskaDHSS/EIS-Modernization#203]
Is there an existing identity and access management solution the person search web application must integrate with? If so, what is it? Will either State of Alaska Active Directory or MyAlaska (or both) integration be required?

**Comment by mheadd** [comment]
Yes, IBM WebSEAL is in use today and is [expected to be used in conjunction with this project](https://github.com/AlaskaDHSS/DevSecOpsMvp/tree/master/webseal).
