### ISSUE TITLE
Working RFP Draft Question - Scrum master or equivalent

### ISSUE THREAD

**Issue by ChrisLetterman** [AlaskaDHSS/EIS-Modernization#205]
Is the contractor expected to fulfill the role of Scrum master or equivalent, or is this role going to be fulfilled by either 18F or the State of Alaska?

**Comment by ctro** [comment]
Yes, the contractor is expected to fill the Scrum Master role. Please see the "How we work" document for more information: https://github.com/AlaskaDHSS/acq-alaska-dhss-modernization/blob/master/how-we-work.md
