### ISSUE TITLE
Working RFP Draft Question - Repository

### ISSUE THREAD

**Issue by ChrisLetterman** [AlaskaDHSS/EIS-Modernization#208]
What restrictions / protections must be in place for the repository? Will code be expected to be protected by any authentication mechanism?

**Comment by randyhart** [comment]
This question was answered in PR #217 and #219.  We mistakenly forgot to include the open source license requirements in our previous draft.  See section 3.21.

**Comment by randyhart** [comment]
Clarification: 
We will use a git repository in Alaska's Microsoft Visual Studio Team Services subscription. VSTS handles restriction/protection via authentication, and various gates on code merges. See details in the [DevSecOps repo] (https://github.com/AlaskaDHSS/DevOpsMvp/blob/ac8b47530b3114636e5cfe6ee8bab5c04cdf01e5/vsts/GitBranchingStrategy.md)
