### ISSUE TITLE
Working RFP Draft Question - Deployment Location

### ISSUE THREAD

**Issue by ChrisLetterman** [AlaskaDHSS/EIS-Modernization#209]
Will the envisioned end solution be hosted in the cloud or on Alaska infrastructure (on-premises)?

**Comment by cefolar** [comment]
From what I understand of the technology stack the desire is for it to be hosted in the Microsoft Azure Cloud.  I am assuming the Azure Govt Cloud - but I don't know if that has been specified.

**Comment by randyhart** [comment]
The end solution will be hosted in the Azure cloud environment as outlined in the DevSecOps repo.
