### ISSUE TITLE
Working RFP Draft Question - Code Security

### ISSUE THREAD

**Issue by ChrisLetterman** [AlaskaDHSS/EIS-Modernization#212]
What constraints will be applied to the project regarding Alaska citizen privacy and the security of sensitive information given the code is to be open-source, transparent and publicly accessible? Freely accessible code could allow a bad actor to mount a successful cyber security attack.

**Comment by ctro** [comment]
Our use of open source on this project is informed by best practices in the software industry including government policies on use of open source like GSA's Open Source Policy and OMB M-16-21 which direct all federal agencies to adopt open source software practices. Please see the DevSecOps repo in AlaskaDHSS organization for a more complete discussion of our security practices and tools for this project.

**Comment by ChrisLetterman** [comment]
Thank you for the feedback. I certainly agree there is responsibility to ensure secure coding practices are known and followed. I've a follow up question concerning the ATO and the "Before you ship" document. From my perspective, the document describes a predominantly Federally-flavored security approach for system acquisition and deployment. Can you confirm this project will follow the Federal or a State of Alaska security approach? If it is the later, will there be a similar "Before you ship" or an ATO process to follow to meet the state's security expectation?

**Comment by randyhart** [comment]
The [before-you-ship document](https://before-you-ship.18f.gov/ato/) linked by @cryptofilegsa is worth reading but informational only - our goal is to work with the state CISO to implement IT Security best practices into our processes.  The practices included in that document are where we want to go as we implement DHSS modernization.

The state of Alaska, not the federal government, is responsible for granting an ATO.  This is an area that we are still refining within our team and with the IT Security personnel that are assisting us with this acquisition.
