### ISSUE TITLE
Working RFP Draft Question - Data Access (ADABAS)

### ISSUE THREAD

**Issue by ChrisLetterman** [AlaskaDHSS/EIS-Modernization#213]
EIS data is currently stored in ADABAS on the State of Alaska mainframe. Has a strategy to query the data-set from the mainframe been formulated? If so, would it require additional skill-sets and expertise not currently listed in the Git website?

**Comment by randyhart** [comment]
@ChrisLetterman thanks for all of these questions.  We wanted to let you know that we're working on responses to all of them.  Thanks for your interest in this project.

**Comment by ChrisLetterman** [comment]
@randyhart Appreciate that feedback!

**Comment by randyhart** [comment]
We explored several different methods of accessing EIS data that are outlined in more detail in the [prototype findings document](https://github.com/AlaskaDHSS/acq-alaska-dhss-modernization/blob/master/procurement-docs-search/prototype-findings.md)

**Comment by mheadd** [comment]
Just an FYI since you've had questions about this project - the RFP has now been issued, and you can [find details here](https://github.com/AlaskaDHSS/RFP-Search-Unification).
