### ISSUE TITLE
Release/Issue Date of the RFP

### ISSUE THREAD

**Issue by GiViCNW** [AlaskaDHSS/EIS-Modernization#233]
Has the RFP been released? The issue date stated Oct 26, 2017. If yes, where will it be released? Thx

**Comment by jongeselle** [comment]
The 26th was our goal. We are still tying up a few loose ends and hope to have the RFP posted early next week.

**Comment by randyhart** [comment]
Just a reminder to ourselves - we'll need to update the dates in the RFP and in the [Readme for the first procurement repo](https://github.com/AlaskaDHSS/RFP-Search-Unification) once we release the formal RFP.

**Comment by randyhart** [comment]
This was fixed in PR #240 - the final RFP will be released on November 3, 2017.

**Comment by JMHamaker** [comment]
Thanks, yes I had the same question. Please confirm the draft dated 11-3 now has been officially released? Due 11/27 still? Thank you!

**Comment by randyhart** [comment]
Yes - the final RFP was released.  The repo for the new RFP can be found [here.](https://github.com/AlaskaDHSS/RFP-Search-Unification)

**Comment by JMHamaker** [comment]
Great, thanks!
