### ISSUE TITLE
Procurement Strategy Summary

### ISSUE THREAD

**Issue by mheadd** [AlaskaDHSS/EIS-Modernization#293]
We should have a [place in the repo](https://github.com/AlaskaDHSS/EIS-Modernization/blob/scoping-changes/README.md#methods--strategies) where we briefly summarize the overall procurement strategy and the various strategies / tactics that are employed as part of each RFP. There are pieces of this in different places across the repo, but s centralized place for this kind of summary would be helpful going forward.

The items this summary c/should include:
- drafting in the open
- vendor feedback
- short proposals
- point systems
- goals not reqs
- shorter/smaller budget
- etc

**Comment by nfaulknerAK** [comment]
This list looks good. I would only add a heavy emphasis on the strategy of rapid prototyping and how it informs a procurement.
