### ISSUE TITLE
NEW SUPPORT RFP HAS BEEN RELEASED!!

### ISSUE THREAD

**Issue by nfaulknerAK** [AlaskaDHSS/EIS-Modernization#321]
There is a new RFP released for bid. 
Interested parties can find out more information at [ARIES SUPPORT RFP](https://github.com/AlaskaDHSS/RFP-ARIES-Support)

**Comment by waldoj** [comment]
😍 This is great and y'all are great and this whole project is great!

**Comment by monicaw2** [comment]
Awww.. I miss working with you guys!
