### ISSUE TITLE
How will system integration be managed?

### ISSUE THREAD

**Issue by waldoj** [AlaskaDHSS/EIS-Modernization#50]
It appears system integration is an ongoing strategic concern. What does this mean for the State as far as managing the system integration? If the State will not use system integration how does DHSS vision the integration and workflow management of multiple vendors across multiple procurements and across multiple departmental initiatives?

**Comment by mtorres253** [comment]
Alaska is addressing this concern by teaming with 18F to transition to the role of product ownership and requiring vendors to develop the components in the open with well documented code.
