### ISSUE TITLE
What contract vehicle will be used for modular?

### ISSUE THREAD

**Issue by waldoj** [AlaskaDHSS/EIS-Modernization#77]
What contract vehicle do you anticipate using for modular procurements (e.g. competitive sealed proposals for a master contract, competitive sealed proposals for each module, State of Alaska Task Order Procurement System (TOPS))?

**Comment by randyhart** [comment]
Alaska will post the RFP on their [Vendor Self Service portal](https://iris-vss.alaska.gov/) and to GitHub for open competition.
