### ISSUE TITLE
Is there a phased approach planned?

### ISSUE THREAD

**Issue by waldoj** [AlaskaDHSS/EIS-Modernization#90]
Is Alaska DHSS planning a phased-in approach with the programs and in what sequence?

**Comment by randyhart** [comment]
Please review the [Project Readme](https://github.com/18F/acq-alaska-dhss-modernization/blob/master/README.md) and the [Product Roadmap.](https://app.mural.ly/t/gsa6/m/gsa6/1493828126408/view/2807948360)
