### ISSUE TITLE
What programs are within scope?

### ISSUE THREAD

**Issue by waldoj** [AlaskaDHSS/EIS-Modernization#91]
Will Alaska DHSS share what programs are being considered in the scope of the project?

**Comment by randyhart** [comment]
Please review the [Project Readme](https://github.com/18F/acq-alaska-dhss-modernization/blob/master/README.md) and the [Product Roadmap.](https://app.mural.ly/t/gsa6/m/gsa6/1493828126408/view/2807948360)
